openapi: 3.0.1
info:
  title: Product Catalog Management agreement serviceCandidate API
  description: "Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products. \n### Operations\nProduct Catalog API performs the following operations on the resources :\n- Retrieve an entity or a collection of entities depending on filter criteria\n- Partial update of an entity (including updating rules)\n- Create an entity (including default values and creation rules)\n- Delete an entity\n- Manage notification of events"
  version: 5.0.0
servers:
- url: https://serverRoot/productCatalogManagement/v5/
tags:
- name: serviceCandidate
paths:
  /serviceCandidate:
    get:
      operationId: listServiceCandidate
      summary: List or find ServiceCandidate objects
      description: This operation list or find ServiceCandidate entities
      tags:
      - serviceCandidate
      parameters:
      - name: fields
        description: Comma-separated properties to be provided in response
        required: false
        in: query
        type: string
      - name: offset
        description: Requested index for start of resources to be provided in response
        required: false
        in: query
        type: integer
      - name: limit
        description: Requested number of resources to be provided in response
        required: false
        in: query
        type: integer
      responses:
        '200':
          description: Success
          headers:
            X-Result-Count:
              description: Actual number of items returned in the response body
              type: integer
            X-Total-Count:
              description: Total number of items matching criteria
              type: integer
          schema:
            type: array
            items:
              $ref: '#/definitions/ServiceCandidate'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        '405':
          description: Method Not allowed
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
    post:
      operationId: createServiceCandidate
      summary: Creates a ServiceCandidate
      description: This operation creates a ServiceCandidate entity.
      tags:
      - serviceCandidate
      parameters:
      - name: serviceCandidate
        description: The ServiceCandidate to be created
        required: true
        schema:
          $ref: '#/definitions/ServiceCandidate_Create'
        in: body
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/ServiceCandidate'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/Error'
        '405':
          description: Method Not allowed
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
  /serviceCandidate/{id}:
    get:
      operationId: retrieveServiceCandidate
      summary: Retrieves a ServiceCandidate by ID
      description: This operation retrieves a ServiceCandidate entity. Attribute selection is enabled for all first level attributes.
      tags:
      - serviceCandidate
      parameters:
      - name: id
        description: Identifier of the ServiceCandidate
        required: true
        type: string
        in: path
      - name: fields
        description: Comma-separated properties to provide in response
        required: false
        type: string
        in: query
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ServiceCandidate'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        '405':
          description: Method Not allowed
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
    patch:
      operationId: patchServiceCandidate
      summary: Updates partially a ServiceCandidate
      description: This operation updates partially a ServiceCandidate entity.
      tags:
      - serviceCandidate
      parameters:
      - name: id
        description: Identifier of the ServiceCandidate
        required: true
        type: string
        in: path
      - name: serviceCandidate
        description: The ServiceCandidate to be updated
        required: true
        schema:
          $ref: '#/definitions/ServiceCandidate_Update'
        in: body
      responses:
        '200':
          description: Updated
          schema:
            $ref: '#/definitions/ServiceCandidate'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        '405':
          description: Method Not allowed
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
    delete:
      operationId: deleteServiceCandidate
      summary: Deletes a ServiceCandidate
      description: This operation deletes a ServiceCandidate entity.
      tags:
      - serviceCandidate
      parameters:
      - name: id
        description: Identifier of the ServiceCandidate
        required: true
        type: string
        in: path
      responses:
        '204':
          description: Deleted
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        '405':
          description: Method Not allowed
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    description: Used when an API throws an Error, typically with a HTTP error response-code (3xx, 4xx, 5xx)
    type: object
    required:
    - code
    - reason
    properties:
      code:
        type: string
        description: Application relevant detail, defined in the API or a common list.
      reason:
        type: string
        description: Explanation of the reason for the error which can be shown to a client user.
      message:
        type: string
        description: More details and corrective actions related to the error which can be shown to a client user.
      status:
        type: string
        description: HTTP Error code extension
      referenceError:
        type: string
        format: uri
        description: URI of documentation describing the error.
      '@baseType':
        type: string
        description: When sub-classing, this defines the super-class.
      '@schemaLocation':
        type: string
        format: uri
        description: A URI to a JSON-Schema file that defines additional attributes and relationships
      '@type':
        type: string
        description: When sub-classing, this defines the sub-class entity name.
  ServiceCategoryRef:
    type: object
    description: The (service) category resource is used to group service candidates in logical containers. Categories can contain other categories.
    properties:
      id:
        type: string
        description: unique identifier
      href:
        type: string
        format: uri
        description: Hyperlink reference
      name:
        type: string
        description: Name of the related entity.
      version:
        type: string
        description: Category version
      '@baseType':
        type: string
        description: When sub-classing, this defines the super-class
      '@schemaLocation':
        type: string
        format: uri
        description: A URI to a JSON-Schema file that defines additional attributes and relationships
      '@type':
        type: string
        description: When sub-classing, this defines the sub-class Extensible name
      '@referredType':
        type: string
        description: The actual type of the target instance when needed for disambiguation.
    required:
    - id
  ServiceCandidate_Create:
    type: object
    description: 'ServiceCandidate is an entity that makes a service specification available to a catalog. A

      ServiceCandidate and its associated service specification may be published - made visible - in any number of service catalogs, or in none. One service specification can be composed of other service specifications.

      Skipped properties: id,href'
    required:
    - name
    - serviceSpecification
    properties:
      description:
        type: string
        description: Description of this REST resource
      lastUpdate:
        type: string
        format: date-time
        description: Date and time of the last update of this REST resource
      lifecycleStatus:
        type: string
        description: Used to indicate the current lifecycle status of the service candidate.
      name:
        type: string
        description: Name given to this REST resource
      version:
        type: string
        description: the version of service candidate
      category:
        type: array
        items:
          $ref: '#/definitions/ServiceCategoryRef'
        description: List of categories for this candidate
      serviceSpecification:
        $ref: '#/definitions/ServiceSpecificationRef'
        description: The service specification implied by this candidate
      validFor:
        $ref: '#/definitions/TimePeriod'
        description: The period for which this REST resource is valid
      '@baseType':
        type: string
        description: When sub-classing, this defines the super-class
      '@schemaLocation':
        type: string
        format: uri
        description: A URI to a JSON-Schema file that defines additional attributes and relationships
      '@type':
        type: string
        description: When sub-classing, this defines the sub-class Extensible name
  TimePeriod:
    type: object
    description: A period of time, either as a deadline (endDateTime only) a startDateTime only, or both
    properties:
      endDateTime:
        example: '1985-04-12T23:20:50.52Z'
        type: string
        format: date-time
        description: End of the time period, using IETC-RFC-3339 format
      startDateTime:
        example: '1985-04-12T23:20:50.52Z'
        type: string
        format: date-time
        description: Start of the time period, using IETC-RFC-3339 format
  ServiceCandidate:
    type: object
    description: 'ServiceCandidate is an entity that makes a service specification available to a catalog. A

      ServiceCandidate and its associated service specification may be published - made visible - in any number of service catalogs, or in none. One service specification can be composed of other service specifications.'
    properties:
      id:
        type: string
        description: unique identifier
      href:
        type: string
        format: uri
        description: Hyperlink reference
      description:
        type: string
        description: Description of this REST resource
      lastUpdate:
        type: string
        format: date-time
        description: Date and time of the last update of this REST resource
      lifecycleStatus:
        type: string
        description: Used to indicate the current lifecycle status of the service candidate.
      name:
        type: string
        description: Name given to this REST resource
      version:
        type: string
        description: the version of service candidate
      category:
        type: array
        items:
          $ref: '#/definitions/ServiceCategoryRef'
        description: List of categories for this candidate
      serviceSpecification:
        $ref: '#/definitions/ServiceSpecificationRef'
        description: The service specification implied by this candidate
      validFor:
        $ref: '#/definitions/TimePeriod'
        description: The period for which this REST resource is valid
      '@baseType':
        type: string
        description: When sub-classing, this defines the super-class
      '@schemaLocation':
        type: string
        format: uri
        description: A URI to a JSON-Schema file that defines additional attributes and relationships
      '@type':
        type: string
        description: When sub-classing, this defines the sub-class Extensible name
  ServiceSpecificationRef:
    type: object
    description: 'Service specification reference: ServiceSpecification(s) required to realize a ProductSpecification.'
    properties:
      id:
        type: string
        description: unique identifier
      href:
        type: string
        format: uri
        description: Hyperlink reference
      name:
        type: string
        description: Name of the related entity.
      version:
        type: string
        description: Service specification version
      '@baseType':
        type: string
        description: When sub-classing, this defines the super-class
      '@schemaLocation':
        type: string
        format: uri
        description: A URI to a JSON-Schema file that defines additional attributes and relationships
      '@type':
        type: string
        description: When sub-classing, this defines the sub-class Extensible name
      '@referredType':
        type: string
        description: The actual type of the target instance when needed for disambiguation.
    required:
    - id
  ServiceCandidate_Update:
    type: object
    description: 'ServiceCandidate is an entity that makes a service specification available to a catalog. A

      ServiceCandidate and its associated service specification may be published - made visible - in any number of service catalogs, or in none. One service specification can be composed of other service specifications.

      Skipped properties: id,href,lastUpdate'
    properties:
      description:
        type: string
        description: Description of this REST resource
      lifecycleStatus:
        type: string
        description: Used to indicate the current lifecycle status of the service candidate.
      name:
        type: string
        description: Name given to this REST resource
      version:
        type: string
        description: the version of service candidate
      category:
        type: array
        items:
          $ref: '#/definitions/ServiceCategoryRef'
        description: List of categories for this candidate
      serviceSpecification:
        $ref: '#/definitions/ServiceSpecificationRef'
        description: The service specification implied by this candidate
      validFor:
        $ref: '#/definitions/TimePeriod'
        description: The period for which this REST resource is valid
      '@baseType':
        type: string
        description: When sub-classing, this defines the super-class
      '@schemaLocation':
        type: string
        format: uri
        description: A URI to a JSON-Schema file that defines additional attributes and relationships
      '@type':
        type: string
        description: When sub-classing, this defines the sub-class Extensible name
